backend:
  name: github
  repo: weallsweden/weall-sweden-site
  branch: main
  base_url: https://poetic-sable-61a3b9.netlify.app
  auth_endpoint: api/auth

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/pages/index.sv.md"
        label: "Start (SV)"
        name: "index_sv"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
