backend:
  name: git-gateway
  branch: main
media_folder: "public/images"
public_folder: "/images"
collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/pages/index.sv.md"
        label: "Start (SV)"
        name: "index_sv"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }