backend:
  name: oauth2
  auth_type: oauth2
  base_url: https://dev-mv6ghq2w53eenka2.eu.auth0.com
  auth_endpoint: authorize
  app_id: Ov23liFA1jTt1WriABxj
  token_endpoint: oauth/token
  repo: weall-sweden/weall-sweden-site
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/pages/index.sv.md"
        label: "Start (SV)"
        name: "index_sv"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
